// Sample product dataset
import { Product } from "./types";

export const sampleProducts: Product[] = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    category: "Electronics",
    brand: "SoundMax",
    price: 79.99,
    rating: 4.5,
    inStock: true,
    description: "Premium noise-cancelling wireless headphones with 30-hour battery life",
  },
  {
    id: 2,
    name: "Ergonomic Office Chair",
    category: "Furniture",
    brand: "ComfortPlus",
    price: 299.99,
    rating: 4.8,
    inStock: true,
    description: "Adjustable lumbar support office chair with breathable mesh",
  },
  {
    id: 3,
    name: "Stainless Steel Water Bottle",
    category: "Home & Kitchen",
    brand: "HydroFlow",
    price: 24.99,
    rating: 4.3,
    inStock: true,
    description: "Insulated 32oz water bottle keeps drinks cold for 24 hours",
  },
  {
    id: 4,
    name: "Mechanical Gaming Keyboard",
    category: "Electronics",
    brand: "KeyMaster",
    price: 149.99,
    rating: 4.7,
    inStock: false,
    description: "RGB backlit mechanical keyboard with blue switches",
  },
  {
    id: 5,
    name: "Yoga Mat with Carrying Strap",
    category: "Sports",
    brand: "FlexFit",
    price: 39.99,
    rating: 4.6,
    inStock: true,
    description: "Non-slip 6mm thick yoga mat perfect for all exercises",
  },
  {
    id: 6,
    name: "Smart Watch Pro",
    category: "Electronics",
    brand: "TechWear",
    price: 199.99,
    rating: 4.4,
    inStock: true,
    description: "Fitness tracking smartwatch with heart rate monitor and GPS",
  },
  {
    id: 7,
    name: "Coffee Maker Deluxe",
    category: "Home & Kitchen",
    brand: "BrewMaster",
    price: 89.99,
    rating: 4.2,
    inStock: true,
    description: "Programmable 12-cup coffee maker with thermal carafe",
  },
  {
    id: 8,
    name: "Running Shoes Elite",
    category: "Sports",
    brand: "SprintMax",
    price: 129.99,
    rating: 4.9,
    inStock: true,
    description: "Lightweight cushioned running shoes for maximum comfort",
  },
  {
    id: 9,
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    brand: "SoundMax",
    price: 59.99,
    rating: 4.5,
    inStock: false,
    description: "Waterproof portable speaker with 12-hour battery life",
  },
  {
    id: 10,
    name: "Standing Desk Converter",
    category: "Furniture",
    brand: "ComfortPlus",
    price: 179.99,
    rating: 4.6,
    inStock: true,
    description: "Adjustable height desk converter for ergonomic workspace",
  },
];
